site_name: MoAI-ADK Documentation
site_description: MoAI Agentic Development Kit Documentation
site_url: https://docs.moai-adk.dev
repo_url: https://github.com/modu-ai/moai-adk
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.highlight
  - search.share
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
nav:
- Home: index.md
- Getting Started:
  - Installation: getting-started/installation.md
- Guide:
  - Workflow: guide/workflow.md
- Development:
  - Contributing: development/contributing.md
- Examples:
  - Basic Usage: examples/basic.md
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.tabbed
- toc
plugins:
- search