[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moai-adk"
version = "0.1.24"
description = "🗿 MoAI-ADK: Modu-AI Agentic Development Toolkit for Claude Code Integration"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "MoAI Labs", email = "labs@mo.ai.kr"}
]
keywords = ["ai", "claude-code", "development", "automation", "cli"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "colorama>=0.4.6",
    "click>=8.0.0",
    "toml>=0.10.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=22.0",
    "isort>=5.10",
    "mypy>=1.0",
    "flake8>=5.0",
]

[project.urls]
"Homepage" = "https://github.com/modu-ai/moai-adk"
"Bug Reports" = "https://github.com/modu-ai/moai-adk/issues"
"Source" = "https://github.com/modu-ai/moai-adk"
"Documentation" = "https://docs.moai-adk.dev"

[project.scripts]
moai = "moai_adk.cli:main"
moai-install = "moai_adk.install.post_install:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["moai_adk*"]
exclude = ["tests*", "docs*", "__pycache__*", "legacy*"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
"moai_adk" = [
    "py.typed",
    "resources/**/*",
    "resources/VERSION",
    "resources/templates/**/*",
    "resources/templates/.claude/**/*",
    "resources/templates/.moai/**/*",
    "resources/templates/.github/**/*"
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | legacy
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
